# for local development
version: '3.7'
services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes: 
      - 'pg_data:/var/lib/postgresql/data'
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dtr40_development

  front:
    build:
      context: ./front
    ports:
    - '8080:8080'
    volumes:
    - './front:/app'
    environment:
      VUE_APP_BACK_SERVER: 'http://back:3000'

  back:
    build:
      context: ./back
    ports:
    - '3000:3000'
    volumes:
    - './back:/app'
    environment:
      RAILS_ENV: development
      DATABASE_PASSWORD: postgres
      DATABASE_USER: postgres
      DATABASE_HOST: db

volumes:
  pg_data: