default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 6 } %>
  port:     5432
  host:     <%= ENV.fetch('DATABASE_HOST',     'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER',     'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  database: <%= ENV.fetch('DATABASE_NAME',     'spezi_challenge') %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
